---
abstract: 'interface to secure password storage(s)'
author:
  - 'Marcin Kasperski <Marcin.Kasperski@mekk.waw.pl>'
build_requires:
  Passwd::Keyring::Memory: '0.24'
  Pod::Readme: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
keywords:
  - passwords
  - security
  - secure-storage
  - keyring
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Passwd-Keyring-Auto
provides:
  Passwd::Keyring::Auto:
    file: lib/Passwd/Keyring/Auto.pm
    version: '0.2704'
  Passwd::Keyring::Auto::KeyringAPI:
    file: lib/Passwd/Keyring/Auto/KeyringAPI.pm
recommends:
  Passwd::Keyring::Gnome: '0.25'
  Passwd::Keyring::KDEWallet: '0.20'
requires:
  File::ShareDir: '1.00'
  Passwd::Keyring::Memory: '0.24'
  perl: v5.6.0
resources:
  bugtracker: https://bitbucket.org/Mekk/perl-keyring-auto/issues
  homepage: http://bitbucket.org/Mekk/perl-keyring-auto
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/Mekk/perl-keyring-auto
version: '0.2704'
